### PR TITLE
Add keyboard backlight timeout

### PR DESCRIPTION
**Pull request by sermart1234**
Tested on Honor Magicbook Pro 2020

### CODE REVIEW

**Comment by aymanbagabas** [comment]
@sermart1234 Thanks for putting up this awesome work. Could you please upload a acpidump and your `dmidecode` output? I like to keep a record of all the devices that this driver supports.

**Comment by sermart1234** [comment]
@aymanbagabas, acpidump and dmidecode output. See method op code in SSDT7 
[Honor Magicbook Pro 16.1 2020 with Ryzen 4600H.zip](https://github.com/aymanbagabas/Huawei-WMI/files/5542967/Honor.Magicbook.Pro.16.1.2020.with.Ryzen.4600H.zip)

**Comment by aymanbagabas** [comment]
I'm trying to test this on my machines the Matebook X Pro (MACH-WX9) but it looks like it doesn't have this feature. I don't have the `\SKBT` and `\GKBT` in the firmware. It might be included in the new firmware update 1.30 but I couldn't get the update to work using `fwupd` and `firmware-packeger` and I don't have a Windows installation.

@nekr0z @german-rios-gonzalez could you guys test this PR on your machines? I'd recommend upgrading to the latest firmware if possible.

**Comment by aymanbagabas** [comment]
One more thing, could you please rebase this pr on [feat/kbdlight](https://github.com/aymanbagabas/Huawei-WMI/tree/feat/kbdlight)

**Pull request closed without merging**
