### PR TITLE
add power unlock

### PR DESCRIPTION
**Pull request by sermart1234**
Switching between performance mode and balanced mode as in PC manager

### CODE REVIEW

**Comment by aymanbagabas** [comment]
Hey @sermart1234 thank you for the PR!

Would you mind describing what this power unlock function does? 

Also I'm working on improving the driver by queuing work in a queue rather than executing them asynchronous. Would you mind trying the `wq` branch? This should be eliminate race conditions when changing battery thresholds multiple times consecutively for instance.

**Comment by sermart1234** [comment]
> Would you mind describing what this power unlock function does?

+/- nothing
Increases the temperature limit. +100 MHz.
On Linux
https://browser.geekbench.com/v5/cpu/12508707 - balanced
https://browser.geekbench.com/v5/cpu/12508831 - perfomance
On Windows + graphics
Google Translate: https://4pda-to.translate.goog/forum/index.php?showtopic=998908&st=5040&_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp#entry111254101
Orig: https://4pda.to/forum/index.php?s=&showtopic=998908&view=findpost&p=111254101

**Review by egormanga — APPROVED** [review]

**Comment by sermart1234** [comment]
power_unlock increases the power limit by 5 watts.

You can change stapm-limit and slow-limit using [RyzenAdj](https://github.com/FlyGoat/RyzenAdj)

**Comment by egormanga** [comment]
> using [RyzenAdj](https://github.com/FlyGoat/RyzenAdj)

To be clear: `RyzenAdj` works only on laptops with AMD Ryzen CPUs.

**Pull request merged**
