### PR TITLE
add keyboard backlight timeout

### PR DESCRIPTION
**Pull request by sermart1234**

### CODE REVIEW

**Review by egormanga — APPROVED** [review]
Works on Honor MagicBook 14 2021 (Intel Core i5, model NDR-WDH9HN).

**Comment by sermart1234** [comment]
@egormanga does micmite LED work?

**Comment by egormanga** [comment]
Everything already implemented works.

**Comment by aymanbagabas** [comment]
This doesn't work on my 2018 Matebook Pro. I'll merge this and wait for more feedback from other users.

**Comment by aymanbagabas** [comment]
https://github.com/aymanbagabas/Huawei-WMI/issues/38#issuecomment-754225940 reported that the kbdlight features only work for devices released in 2020 and after. Would someone please make a PR with a quirk that matches all the devices released before 2020?

**Comment by zaripovrdm** [comment]
Hi, I never worked with low-level linux driver programming, just saw interesting feature for me and decided to compile this project in Fedora 34 using attached readme, but it failed:
`sudo make install
make -C /lib/modules/5.13.12-200.fc34.x86_64/build/ M=/home/roman/driver/Huawei-WMI modules_install
make[1]: Entering directory '/usr/src/kernels/5.13.12-200.fc34.x86_64'
  INSTALL /lib/modules/5.13.12-200.fc34.x86_64/extra/huawei-wmi.ko
  SIGN    /lib/modules/5.13.12-200.fc34.x86_64/extra/huawei-wmi.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  /lib/modules/5.13.12-200.fc34.x86_64
make[1]: Leaving directory '/usr/src/kernels/5.13.12-200.fc34.x86_64'
depmod -a
`
hope it helps you to improve readme or fix some issues

**Comment by aymanbagabas** [comment]
@zaripovrdm this error is basically telling you that signing the module failed. But that doesn't mean the build failed. You could try this https://github.com/andikleen/simple-pt/issues/8#issuecomment-813438385

**Comment by zaripovrdm** [comment]
@aymanbagabas thank you for reply. Your solution works fine, everything installed without errors or warnings.
But with no effect (positive or negative) and directory /sys/devices/platform/huawei-wmi completely disappeared.
device huawei matebook x pro 2021

**Comment by nenkoru** [comment]
Working confirmed on MXP 2020(i7)

**Comment by www159** [comment]
it worked perfectly on my laptop

MatebookD14 ryzen 5(2020)

```txt
Handle 0x0001, DMI type 1, 27 bytes
System Information
        Manufacturer: HUAWEI
        Product Name: NBLL-WXX9
        Version: M1040
        Serial Number: 6DSPM20720001666
        UUID: 1b7bd74e-311e-48b1-b92e-18d7676f51af
        Wake-up Type: Power Switch
        SKU Number: C233
        Family: MateBook D
```

**Pull request merged**
