### PR TITLE
Disable micmute led setup for MRC-WX0 model

### PR DESCRIPTION
**Pull request by Codeman-from-unknown-city**
My notebook doesn't have microphone button led and driver always writes annoying error logs.

image

 I disabled led registration for the model.

### CODE REVIEW

**Comment by aymanbagabas** [comment]
Thank you for the PR! Does this model have a micmute LED?
CC: @sermart1234

**Comment by aymanbagabas** [comment]
Could you upload your `acpidump` please?

**Comment by Codeman-from-unknown-city** [comment]
Could you tell me how to do that?)

**Comment by sermart1234** [comment]
@Codeman-from-unknown-city please
```
sudo acpidump > acpudump
sudo dmidecode > dmidecode.txt
```

**Comment by sermart1234** [comment]
@aymanbagabas I'm working on an LED system. I want to add a check before creating a device file.

**Comment by Codeman-from-unknown-city** [comment]
> 
[acpidump.txt](https://github.com/aymanbagabas/Huawei-WMI/files/8638661/acpidump.txt)
[dmidecode.txt](https://github.com/aymanbagabas/Huawei-WMI/files/8638662/dmidecode.txt)

**Comment by sermart1234** [comment]
@Codeman-from-unknown-city @aymanbagabas ACPI don't have method SMLS. We can check the quirk and not create a device file.

**Comment by aymanbagabas** [comment]
> @Codeman-from-unknown-city @aymanbagabas ACPI don't have method SMLS. We can check the quirk and not create a device file.

@sermart1234 

Well instead of having a quirk, we could add a `micmute_led_available` bool and check if the function is available as well as a module option to disable the led `disable_micmute_led`. This way we don't need a quirk and will also have a generic way to disable the led.

**Comment by sermart1234** [comment]
@aymanbagabas Yes. I want check method SMLS. My English is bad

**Pull request closed without merging**
